/**
 * Prompts App — the standalone page for prompt notes.
 *
 * Prompt notes (template 'prompt') used to be surfaced inside the Notes app
 * (a "Prompts" filter + the editor's config panel). As of 2026-07 they have
 * their own page and are hidden from Notes lists entirely. The BACKEND IS
 * UNCHANGED: a prompt is still a note in the shared `notes` blob, read and
 * written through NotePrompts — so sync, the assistant's scheduled-prompt
 * tools, and the PromptFeed scheduler keep working untouched. This file is
 * UI only.
 *
 * Three in-page views:
 *  - list:   every prompt note in the active profile
 *  - detail: one prompt — body, config chips, actions, recent feed posts
 *  - form:   create/edit (ported from PromptFeed's old "Manage prompts"
 *            modal; reuses its .prompt-mgr-* classes so the styling carries)
 *
 * Entry points: the left-nav tile, Home feed's "Manage prompts" / "+ New"
 * buttons, the feed post overlay's prompt link, and Browse's prompts shelf
 * (all via AppManager.openApp('prompts') / PromptsApp.open()).
 */

const PromptsApp = {
    _view: 'list',      // 'list' | 'detail' | 'form'
    _openId: null,      // detail target; form target (null = create)
    _bound: false,

    init() {
        if (this._bound) return;
        this._bound = true;
        document.getElementById('prompts-add-btn')?.addEventListener('click', () => {
            this._view = 'form';
            this._openId = null;
            this.render();
        });
    },

    /** External entry: open the page on the list, a detail, or the create form. */
    open(opts = {}) {
        if (opts.create) { this._view = 'form'; this._openId = null; }
        else if (opts.id) { this._view = 'detail'; this._openId = opts.id; }
        else { this._view = 'list'; this._openId = null; }
        AppManager.openApp('prompts');
        this.render();
    },

    // --- Data (all reads go through the notes blob — storage source of truth) ---

    _prompts() {
        let list = NotePrompts.list();
        if (typeof ProfileManager !== 'undefined' && ProfileManager.filterByActiveProfile) {
            list = ProfileManager.filterByActiveProfile(list);
        }
        return list.sort((a, b) =>
            new Date(b.modifiedAt || 0).getTime() - new Date(a.modifiedAt || 0).getTime());
    },

    _note(id) {
        return NotePrompts.list().find(n => n.id === id) || null;
    },

    /** Feed posts generated by this prompt, newest first. */
    _outputs(promptId) {
        const d = StorageManager.get('notes');
        const notes = (d && Array.isArray(d.notes)) ? d.notes : [];
        return notes
            .filter(n => NoteTemplates.resolve(n) === 'feed' && n.feed && n.feed.promptId === promptId)
            .sort((a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0));
    },

    _lastRunLabel(p) {
        const last = (typeof PromptFeed !== 'undefined' && PromptFeed.data) ? PromptFeed.data.runs[p.id] : null;
        return last ? `ran ${PromptFeed._timeAgo(last)}` : 'not run yet';
    },

    _chips(cfg) {
        return [
            cfg.offline
                ? `<span class="prompt-mgr-chip">${UIUtils.escapeHtml(NotePrompts.scheduleLabel(cfg))}</span>`
                : `<span class="prompt-mgr-chip">${cfg.target === 'browser' ? 'runs in Browser' : 'runs in Assistant'}</span>`,
            cfg.web ? '<span class="prompt-mgr-chip">&#127760; web</span>' : '',
            cfg.useContext ? '<span class="prompt-mgr-chip">&#10024; my context</span>' : ''
        ].filter(Boolean).join('');
    },

    // --- Render ---

    render() {
        const container = document.getElementById('prompts-main');
        if (!container) return;
        // The open prompt may have been deleted (or synced away).
        if (this._openId && !this._note(this._openId)) {
            this._view = 'list';
            this._openId = null;
        }
        if (this._view === 'form') this._renderForm(container, this._openId ? this._note(this._openId) : null);
        else if (this._view === 'detail') this._renderDetail(container, this._note(this._openId));
        else this._renderList(container);
    },

    _renderList(container) {
        const prompts = this._prompts();
        // The page's one organizing idea: scheduled prompts (background runs
        // that post to the Home feed) vs on-demand ones you run by hand.
        const scheduled = [], onDemand = [];
        for (const p of prompts) (NotePrompts.config(p).offline ? scheduled : onDemand).push(p);

        const row = (p) => {
            const cfg = NotePrompts.config(p);
            return `
                <div class="prompt-mgr-row prompts-row" data-open-prompt="${p.id}" role="button" tabindex="0">
                    <span class="prompt-mgr-row-icon" aria-hidden="true">${cfg.offline ? '&#9201;' : '&#9889;'}</span>
                    <div class="prompt-mgr-row-main">
                        <div class="prompt-mgr-row-title">${UIUtils.escapeHtml(p.title || 'Untitled prompt')}</div>
                        <div class="prompt-mgr-row-meta">${this._chips(cfg)}${cfg.offline ? `<span class="prompt-mgr-row-ran">${this._lastRunLabel(p)}</span>` : ''}</div>
                    </div>
                    <div class="prompt-mgr-row-actions">
                        <button class="prompt-mgr-run" data-run="${p.id}" type="button" title="Run this prompt now">&#9654; Run</button>
                        <button class="prompt-mgr-iconbtn" data-edit="${p.id}" type="button" title="Edit" aria-label="Edit">&#9998;</button>
                        <button class="prompt-mgr-iconbtn prompt-mgr-del" data-del="${p.id}" type="button" title="Delete" aria-label="Delete">&#128465;</button>
                    </div>
                </div>`;
        };

        const section = (label, hint, list) => !list.length ? '' : `
            <div class="prompts-section">
                <div class="prompts-section-head">
                    <span class="prompts-section-label">${label}</span>
                    <span class="prompt-mgr-count">${list.length}</span>
                    <span class="prompts-section-hint">${hint}</span>
                </div>
                <div class="prompt-mgr-list prompts-page-list">${list.map(row).join('')}</div>
            </div>`;

        const empty = `
            <div class="prompt-mgr-empty">
                <span class="prompt-mgr-empty-icon" aria-hidden="true">&#9889;</span>
                <p class="prompt-mgr-empty-text">No prompts yet. A prompt is a reusable instruction — run it in the AI Assistant<br>or on a schedule in the background, posting results to your Home feed.</p>
                <button class="primary-btn prompt-mgr-empty-add" type="button">Create your first prompt</button>
            </div>`;

        container.innerHTML = prompts.length
            ? section('Scheduled', 'runs in the background, posts to your Home feed', scheduled)
                + section('On demand', 'run by hand in the Assistant or Browser', onDemand)
            : `<div class="prompt-mgr-list prompts-page-list">${empty}</div>`;

        container.querySelector('.prompt-mgr-empty-add')?.addEventListener('click', () => {
            this._view = 'form'; this._openId = null; this.render();
        });
        container.querySelectorAll('[data-open-prompt]').forEach(row => {
            row.addEventListener('click', (e) => {
                if (e.target.closest('button')) return;
                this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
            });
            row.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' && !e.target.closest('button')) {
                    this._view = 'detail'; this._openId = row.dataset.openPrompt; this.render();
                }
            });
        });
        container.querySelectorAll('[data-run]').forEach(b =>
            b.addEventListener('click', () => this._runNow(b.dataset.run, b)));
        container.querySelectorAll('[data-edit]').forEach(b =>
            b.addEventListener('click', () => {
                this._view = 'form'; this._openId = b.dataset.edit; this.render();
            }));
        container.querySelectorAll('[data-del]').forEach(b =>
            b.addEventListener('click', () => this._delete(b.dataset.del)));
    },

    _renderDetail(container, note) {
        if (!note) { this._view = 'list'; this._renderList(container); return; }
        const cfg = NotePrompts.config(note);
        const body = NotePrompts.bodyText(note);
        const outputs = this._outputs(note.id).slice(0, 20);

        const postRows = outputs.map(o => {
            const when = o.createdAt
                ? new Date(o.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })
                : '';
            const tmp = document.createElement('div');
            tmp.innerHTML = o.content || '';
            const text = o.feed && o.feed.error
                ? o.feed.error
                : (tmp.textContent || '').replace(/\s+/g, ' ').trim();
            const preview = text.length > 180 ? text.slice(0, 180).trimEnd() + '…' : text;
            return `
                <button class="prompts-post-row${o.feed && o.feed.error ? ' is-error' : ''}" data-open-post="${o.id}" type="button">
                    <span class="prompts-post-when">${when}</span>
                    <span class="prompts-post-preview">${UIUtils.escapeHtml(preview)}</span>
                </button>`;
        }).join('');

        container.innerHTML = `
            <div class="prompt-mgr-head">
                <button class="prompt-mgr-back" data-back type="button" title="Back to prompts" aria-label="Back to prompts">&#8592;</button>
                <span class="prompt-mgr-subtitle">Prompt</span>
                <div class="prompts-detail-actions">
                    <button class="prompt-mgr-run" data-run="${note.id}" type="button" title="Run this prompt now">&#9654; Run now</button>
                    <button class="prompt-mgr-iconbtn" data-edit="${note.id}" type="button" title="Edit" aria-label="Edit">&#9998;</button>
                    <button class="prompt-mgr-iconbtn prompt-mgr-del" data-del="${note.id}" type="button" title="Delete" aria-label="Delete">&#128465;</button>
                </div>
            </div>
            <h3 class="prompts-detail-title">${UIUtils.escapeHtml(note.title || 'Untitled prompt')}</h3>
            <div class="prompt-mgr-row-meta prompts-detail-meta">${this._chips(cfg)}${cfg.offline ? `<span class="prompt-mgr-row-ran">${this._lastRunLabel(note)}</span>` : ''}</div>
            <div class="prompts-detail-body">${UIUtils.escapeHtml(body) || '<span class="prompts-detail-empty">No prompt text yet — edit to add one.</span>'}</div>
            ${outputs.length ? `
                <div class="prompts-outputs">
                    <h4 class="prompt-mgr-label">Feed posts</h4>
                    ${postRows}
                </div>` : (cfg.offline ? '<p class="prompts-detail-empty">No runs yet — results will appear here and on your Home feed.</p>' : '')}
        `;

        container.querySelector('[data-back]')?.addEventListener('click', () => {
            this._view = 'list'; this._openId = null; this.render();
        });
        container.querySelector('[data-run]')?.addEventListener('click', (e) => this._runNow(note.id, e.currentTarget));
        container.querySelector('[data-edit]')?.addEventListener('click', () => {
            this._view = 'form'; this.render();
        });
        container.querySelector('[data-del]')?.addEventListener('click', () => this._delete(note.id));
        container.querySelectorAll('[data-open-post]').forEach(b =>
            b.addEventListener('click', () => {
                if (typeof PromptFeed !== 'undefined' && PromptFeed.openPost) PromptFeed.openPost(b.dataset.openPost);
            }));
    },

    _renderForm(container, note) {
        const cfg = note ? NotePrompts.config(note) : { ...NotePrompts.DEFAULTS };
        const title = note ? (note.title || '') : '';
        const body = note ? NotePrompts.bodyText(note) : '';

        container.innerHTML = `
            <div class="prompt-mgr-head">
                <button class="prompt-mgr-back" data-back type="button" title="Back" aria-label="Back">&#8592;</button>
                <span class="prompt-mgr-subtitle">${note ? 'Edit prompt' : 'New prompt'}</span>
            </div>
            <div class="prompt-mgr-form">
                <label class="prompt-mgr-label" for="prompt-mgr-title">Title</label>
                <input id="prompt-mgr-title" class="prompt-mgr-input" type="text" placeholder="e.g. Morning briefing" value="${UIUtils.escapeHtml(title)}" autocomplete="off" spellcheck="false">

                <label class="prompt-mgr-label" for="prompt-mgr-body">Prompt</label>
                <div class="prompt-mgr-composer">
                    <textarea id="prompt-mgr-body" class="prompt-mgr-textarea" rows="5" placeholder="What should the model generate on each run?">${UIUtils.escapeHtml(body)}</textarea>
                    <div class="prompt-mgr-composer-foot">
                        <label class="prompt-mgr-optchip" title="Let the model search the web during the run">
                            <input type="checkbox" id="prompt-mgr-web" ${cfg.web ? 'checked' : ''}>
                            <span>&#127760; Web search</span>
                        </label>
                        <label class="prompt-mgr-optchip" title="Run through the AI Assistant with your memory, goals, and schedule">
                            <input type="checkbox" id="prompt-mgr-context" ${cfg.useContext ? 'checked' : ''}>
                            <span>&#10024; My context</span>
                        </label>
                    </div>
                </div>

                <label class="prompt-mgr-optchip prompts-sched-toggle" title="Run automatically in the background and post results to the Home feed">
                    <input type="checkbox" id="prompt-mgr-offline" ${cfg.offline ? 'checked' : ''}>
                    <span>&#9201; Run on a schedule</span>
                </label>

                <div class="prompts-sched-fields" ${cfg.offline ? '' : 'hidden'}>
                    <label class="prompt-mgr-label">Run every</label>
                    <input type="hidden" id="prompt-mgr-interval" value="${cfg.interval}">
                    <div class="prompt-mgr-seg" role="group" aria-label="Run every">
                        ${['hourly', '6h', 'daily', 'weekly'].map(v => `
                            <button type="button" class="prompt-mgr-seg-btn ${cfg.interval === v ? 'active' : ''}" data-value="${v}" aria-pressed="${cfg.interval === v}">${NotePrompts.intervalLabel(v)}</button>`).join('')}
                    </div>
                    <div class="prompt-mgr-time-row" ${(cfg.interval === 'daily' || cfg.interval === 'weekly') ? '' : 'hidden'}>
                        <label class="prompt-mgr-label" for="prompt-mgr-time">At (optional)</label>
                        <input type="time" id="prompt-mgr-time" class="prompt-mgr-input prompt-mgr-time" value="${cfg.time || ''}">
                    </div>
                    <p class="prompt-mgr-hint">Runs offline on your local model and posts the result to the Home feed.</p>
                </div>

                <div class="prompts-target-row" ${cfg.offline ? 'hidden' : ''}>
                    <label class="prompt-mgr-label">Runs in</label>
                    <input type="hidden" id="prompt-mgr-target" value="${cfg.target}">
                    <div class="prompt-mgr-seg" role="group" aria-label="Runs in">
                        ${[['agent', 'AI Assistant'], ['browser', 'Browser']].map(([v, l]) => `
                            <button type="button" class="prompt-mgr-seg-btn prompts-target-btn ${cfg.target === v ? 'active' : ''}" data-value="${v}" aria-pressed="${cfg.target === v}">${l}</button>`).join('')}
                    </div>
                </div>

                <div class="prompt-mgr-form-actions">
                    <button class="secondary-btn prompt-mgr-cancel" type="button">Cancel</button>
                    <button class="primary-btn prompt-mgr-save" type="button">${note ? 'Save changes' : 'Create prompt'}</button>
                </div>
            </div>`;

        const back = () => {
            this._view = this._openId ? 'detail' : 'list';
            this.render();
        };
        container.querySelector('[data-back]')?.addEventListener('click', back);
        container.querySelector('.prompt-mgr-cancel')?.addEventListener('click', back);

        // Schedule toggle swaps which config block is visible.
        container.querySelector('#prompt-mgr-offline')?.addEventListener('change', (e) => {
            container.querySelector('.prompts-sched-fields').hidden = !e.target.checked;
            container.querySelector('.prompts-target-row').hidden = e.target.checked;
        });

        // Segmented controls write into their hidden inputs so the save
        // handler reads plain fields (same recipe as the old modal form).
        container.querySelectorAll('.prompt-mgr-seg-btn:not(.prompts-target-btn)').forEach(b =>
            b.addEventListener('click', () => {
                container.querySelector('#prompt-mgr-interval').value = b.dataset.value;
                container.querySelectorAll('.prompt-mgr-seg-btn:not(.prompts-target-btn)').forEach(x => {
                    x.classList.toggle('active', x === b);
                    x.setAttribute('aria-pressed', String(x === b));
                });
                // A run time only makes sense for wall-clock intervals.
                container.querySelector('.prompt-mgr-time-row').hidden =
                    !(b.dataset.value === 'daily' || b.dataset.value === 'weekly');
            }));
        container.querySelectorAll('.prompts-target-btn').forEach(b =>
            b.addEventListener('click', () => {
                container.querySelector('#prompt-mgr-target').value = b.dataset.value;
                container.querySelectorAll('.prompts-target-btn').forEach(x => {
                    x.classList.toggle('active', x === b);
                    x.setAttribute('aria-pressed', String(x === b));
                });
            }));

        // Cmd/Ctrl+Enter from the prompt body saves — same muscle memory as
        // the assistant composer.
        container.querySelector('#prompt-mgr-body')?.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
                e.preventDefault();
                container.querySelector('.prompt-mgr-save')?.click();
            }
        });

        container.querySelector('.prompt-mgr-save')?.addEventListener('click', () => {
            const t = container.querySelector('#prompt-mgr-title').value.trim();
            const b = container.querySelector('#prompt-mgr-body').value.trim();
            if (!b) { UIUtils.showToast('Add a prompt first', 'error'); return; }
            const offline = container.querySelector('#prompt-mgr-offline').checked;
            const interval = container.querySelector('#prompt-mgr-interval').value;
            const config = {
                target: container.querySelector('#prompt-mgr-target').value,
                offline,
                interval,
                time: (offline && (interval === 'daily' || interval === 'weekly'))
                    ? (container.querySelector('#prompt-mgr-time').value || null) : null,
                web: container.querySelector('#prompt-mgr-web').checked,
                useContext: container.querySelector('#prompt-mgr-context').checked
            };
            const saved = note
                ? NotePrompts.update(note.id, { title: t, body: b, config })
                : NotePrompts.create({ title: t, body: b, config });
            // Nudge the scheduler so a newly created/enabled prompt runs soon
            // instead of waiting for the next poll.
            if (offline && typeof PromptFeed !== 'undefined' && PromptFeed.onPromptsChanged) {
                PromptFeed.onPromptsChanged();
            }
            UIUtils.showToast(note ? 'Prompt updated' : (offline ? 'Prompt scheduled' : 'Prompt created'), 'success');
            this._view = 'detail';
            this._openId = saved ? saved.id : this._openId;
            this.render();
        });

        setTimeout(() => container.querySelector('#prompt-mgr-title')?.focus(), 0);
    },

    // --- Actions ---

    async _runNow(id, btn) {
        const note = this._note(id);
        if (!note) return;
        const cfg = NotePrompts.config(note);
        if (cfg.offline) {
            if (typeof PromptFeed === 'undefined' || !PromptFeed.runNow) return;
            if (btn) btn.disabled = true;
            await PromptFeed.runNow(id);
            this.render();
        } else {
            NotePrompts.runDefault(note);
        }
    },

    async _delete(id) {
        const note = this._note(id);
        const ok = await UIUtils.confirm(
            'Delete prompt',
            `Delete &ldquo;${UIUtils.escapeHtml(note?.title || 'this prompt')}&rdquo;? This removes the prompt and stops its scheduled runs. Past feed posts stay.`,
            '🗑️',
            { confirmText: 'Delete' }
        );
        if (!ok) return;
        NotePrompts.remove(id);
        if (typeof PromptFeed !== 'undefined' && PromptFeed.render) PromptFeed.render();
        if (this._openId === id) { this._view = 'list'; this._openId = null; }
        this.render();
    }
};

AppManager.register('prompts', PromptsApp);
